blank_issues_enabled: false
contact_links:
  - name: QQ群
    url: https://wifi-left.github.io/MC-MiniGames/
    about: 遇到问题，请优先前往QQ群提出。QQ群：1075114603
  - name: 官网
    url: https://wifi-left.github.io/MC-MiniGames/
    about: MiniGames 地图的官网
  - name: 其他反馈 | 需要帮助 | Others
    url: https://github.com/wifi-left/Map-MiniGames/discussions/
    about: 通过 Discussions 反馈其他问题。
